theme: jekyll-theme-minimal
title: Sami Souabni's Website
email: samisouabni@protonmail.com
url: "https://sami.souabni.com" # the base hostname & protocol for your site
github_username:  samisouabni
plugins:
  - jemoji

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext